name: bash

on:
  workflow_run:
    workflows:
      - docker
    types: 
      - completed
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: message
      run: echo "Hello my teacher"



