name: bash

on:
  workflow_run:
    workflows:
      - docker
    types: 
      - completed
    branches:
      - master

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: message
      run: echo "Hello my teacher"


#  - name: print-message
#    inputs:
#      parameters:
#      - name: message
#    container:
#      image: alpine:latest
#      command: [sh, -c]
#      args: ["echo result was: {{inputs.parameters.message}}"]




